kafka:
    topic:
        consumer: order-query
server:
    port: 8083
spring:
    cache:
        type: simple
    application:
        name: OrderQuery
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: order-query
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        properties:
            spring.json.trusted.packages: '*'
    datasource:
        url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=pedidos
        username: sa
        password: S@ul0@1982
    jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
